"""db creation

Revision ID: ad2233792751
Revises: 
Create Date: 2020-07-30 13:29:55.052035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2233792751'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aulas',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_nombre', sa.Text(), nullable=True),
    sa.Column('_capacidad', sa.Integer(), nullable=True),
    sa.Column('_tipo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_nombre')
    )
    op.create_table('cursos',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_nombre', sa.Text(), nullable=True),
    sa.Column('_tipo', sa.Text(), nullable=True),
    sa.Column('_creditos', sa.Integer(), nullable=True),
    sa.Column('_semestre', sa.Integer(), nullable=True),
    sa.Column('_lecciones', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_nombre')
    )
    op.create_table('profesores',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_cedula', sa.Integer(), nullable=True),
    sa.Column('_nombre', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_cedula')
    )
    op.create_table('disponibilidades',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_profesor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_profesor_id'], ['profesores._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('profesores_cursos',
    sa.Column('_profesor_id', sa.Integer(), nullable=True),
    sa.Column('_curso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_curso_id'], ['cursos._id'], ),
    sa.ForeignKeyConstraint(['_profesor_id'], ['profesores._id'], )
    )
    op.create_table('dias',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_nombre', sa.Text(), nullable=True),
    sa.Column('_disponibilidad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_disponibilidad_id'], ['disponibilidades._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('horas',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_hora', sa.Text(), nullable=True),
    sa.Column('_dia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_dia_id'], ['dias._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horas')
    op.drop_table('dias')
    op.drop_table('profesores_cursos')
    op.drop_table('disponibilidades')
    op.drop_table('profesores')
    op.drop_table('cursos')
    op.drop_table('aulas')
    # ### end Alembic commands ###
